type Mutation {
  createAuthor(givenName: String, lastName: String, country: String, birthdate: Date): Author
  createBook(title: String, author: ID, genre: String, publicationDate: Date): Book
  updateAuthor(id: ID!, givenName: String, lastName: String, country: String, birthdate: Date): Author
  updateBook(id: ID!, title: String, author: ID, genre: String, publicationDate: Date): Book
  deleteAuthor(id: ID!): Author
  deleteBook(id: ID!): Book
}
